### PR TITLE
Update org secrets with values

### PR DESCRIPTION
**Pull request by heurtematte**

### CODE REVIEW

**Comment by heurtematte** [comment]
@pstankie can you double check the path for PGP_KEY, and PGP_KEY_PASSWORD? according to this ticket/comment: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2745#note_1090177

**Review by atextor — APPROVED** [review]

**Review by chris-volk — APPROVED** [review]

**Comment by netomi** [comment]
LGTM

**Review by netomi — APPROVED** [review]

**Comment by pstankie** [comment]
Looks ok.

**Pull request merged**
